### ISSUE TITLE
TypeError: select_all() got an unexpected keyword argument 'include_event_time'

### ISSUE THREAD

**Issue by Abidzar16** [logicalclocks/feature-store-api#1007]
So, I was following the tutorial from Hopsworks about air quality prediction (https://github.com/logicalclocks/hopsworks-tutorials/blob/master/advanced_tutorials/air_quality/3_feature_views_and_training_dataset.ipynb), and when I tried to assemble a query

```python
query = air_quality_fg.select_all().join(weather_fg.select_all(include_event_time=False))
```

it summons the error message:
```
TypeError: select_all() got an unexpected keyword argument 'include_event_time'
```

Even though the select_all query allows the optional argument 'include_event_time' according to the [documentation](https://docs.hopsworks.ai/feature-store-api/latest/generated/api/feature_group_api/#select_all)

**Comment by davitbzh** [comment]
Hi @Abidzar16 we have recently upgraded Hopsworks app and tutorials. Let me know if you still experience this issue
