### ISSUE TITLE
hsfs import error

### ISSUE THREAD

**Issue by BacharKabalan** [logicalclocks/feature-store-api#1269]
I have installed hsfs version 3.4.8
When i run from hsfs import embedding, i get the following error: 
ImportError: cannot import name 'embedding' from 'hsfs'

Many thanks

Bash

**Comment by kennethmhc** [comment]
@BacharKabalan You need to install hsfs >= 3.7. Also note that if you are following the similarity search tutorial, it does not work against the app.hopsworks.ai yet as it is in version 3.4.
