### ISSUE TITLE
Init_prepared_statement() got an unexpected keyword argument ‘batch’ 

### ISSUE THREAD

**Issue by buseskorkmaz** [logicalclocks/feature-store-api#526]
Hello,

When I tried to use the online feature serving with batch, it does not work. When I use td_meta.init_prepared_statement(batch=True) it throws the following error:
![image](https://user-images.githubusercontent.com/24464017/140910374-0f5c4bd5-71e1-4178-804c-b6dfe61c265c.png)

Also, get_serving_vectors does not work. I am currently using Jupyter Lab inside of Hopsworks. My hsfs version is 2.4.0. I am following this tutorial: https://github.com/logicalclocks/hops-examples/blob/882cd104f87fd5caa153470f89c68bb6a413eca5/notebooks/featurestore/hsfs/serving/feature_vector_model_serving.ipynb

Any recommendations to solve the issue?

Thanks.

**Comment by moritzmeister** [comment]
Hey!

We are not tracking User issues here on GitHub, please use www.community.hopsworks.ai.
Most likely you were using a version of HSFS that wasn't matching the version of your Hopsworks cluster.
