### ISSUE TITLE
Typo in docs - featurestore_id a mandatory parameter when creating a feature group.

### ISSUE THREAD

**Issue by jimdowling** [logicalclocks/feature-store-api#541]
![image](https://user-images.githubusercontent.com/1904928/145727619-3cf984f9-65ea-47a9-9fbc-240706cb78d8.png)

**Comment by moritzmeister** [comment]
This is just the API reference, users are not going to use the constructor, they will always use `fs.create_feature_group` or `fs.get_feature_group` to instantiate a Feature Group object.
